--   Criar a Tabela `receitas`
CREATE TABLE IF NOT EXISTS `receitas` (
    `id_receita` INT(5) NOT NULL,
    `Nome Receita` varchar(40) NOT NULL,
    `Nome do utilizador` varchar(20) NOT NULL,
    `Data` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Descrição` varchar(1000) NOT NULL,
    `Número de pessoas` INT(2) NOT NULL,
    `id_tempo` int(2) NOT NULL,
    `id_dificuldade` INT(1) NOT NULL,
    `ingrediente1`varchar(60) NOT NULL,
    `ingrediente2`varchar(60) NOT NULL,
    `ingrediente3`varchar(60) NOT NULL,
    `ingrediente4`varchar(60) NOT NULL,
    `ingrediente5`varchar(60) NOT NULL,
    `ingrediente6`varchar(60) NOT NULL, 
    `ingrediente7`varchar(60) NOT NULL,
    `ingrediente8`varchar(60),
    `ingrediente9`varchar(60),
    `ingrediente10`varchar(60),
    `preparação1` varchar(300) NOT NULL,
    `preparação2` varchar(300) NOT NULL,
    `preparação3` varchar(300) NOT NULL,
    `preparação4` varchar(300) NOT NULL,
    `preparação5` varchar(300),
    `preparação6` varchar(300),
    `preparação7` varchar(300),
    `preparação8` varchar(300),
    `preparação9` varchar(300),
    `preparação10` varchar(300),
    `preparação11` varchar(300),
    `id_categoria` INT(2) NOT NULL,
    `foto_main` varchar(100) NOT NULL,
    `foto1` varchar(120) NOT NULL,
    `foto2` varchar(120) NOT NULL,
    `foto3` varchar(120) NOT NULL,
    `foto4` varchar(120) NOT NULL,
    `foto5` varchar(120),
    `foto6` varchar(120),
    `foto7` varchar(120),
    `foto8` varchar(120),
    `foto9` varchar(120),
    `foto10` varchar(120),
    `foto11` varchar(120),
    PRIMARY KEY (`id_receita`),
    FOREIGN KEY (`id_tempo`) References tempo(`id_tempo`),
    FOREIGN KEY (`id_dificuldade`) References dificuldade(`id_dificuldade`),
    FOREIGN KEY (`id_categoria`) References categorias(`id_categoria`)
) ENGINE=InnoDB CHARSET=utf8;

INSERT into `receitas` (`id_receita`,`Nome Receita`,`Nome do utilizador`,`Data`,`Descrição`,`Número de pessoas`,`id_tempo`,`id_dificuldade`,`ingrediente1`,`ingrediente2`,`ingrediente3`,`ingrediente4`,`ingrediente5`,`ingrediente6`,`ingrediente7`,`ingrediente8`,`ingrediente9`,`ingrediente10`,`preparação1`,`preparação2`,`preparação3`,`preparação4`,`preparação5`,`preparação6`,`preparação7`,`preparação8`,`preparação9`,`preparação10`,`preparação11`,`id_categoria`,`foto_main`,`foto1`,`foto2`,`foto3`,`foto4`,`foto5`,`foto6`,`foto7`,`foto8`,`foto9`,`foto10`,`foto11`) VALUES
(1,
 'Folhados de salsicha simples',
 'João Felício',
 CURRENT_TIMESTAMP,
 'folhados de salsicha é aquele lanche clássico que toda a gente gosta, principalmente as crianças. Com uma massa fofinha, o nosso folhado de salsicha simples vai fazer sucesso servido como lanche no dia a dia ou na festa de aniversário dos filhos. Essa receita rende até 12 folhados e fica perfeito servido com molhos.',
 6,
 6,
 1,
 '½ xícara de leite morno',
 '1 ovo pequeno',
 '2 colheres de sopa de óleo',
 '1 colher de sopa de açúcar',
 '½ colher de sopa de sal',
'2 xícaras de farinha de trigo (280 gramas)',
 '5 gramas de fermento biológico seco',
 '12 salsichas',
 'água para cozinhar as salsichas',
 '',
 'Separe os ingredientes para preparar o folhado de salsicha simples.',
 'Em uma tigela misture o leite morno e o fermento. Deixe descansar por 5 minutos.',
 'Em seguida adicione o ovo, o óleo e o açúcar. Misture bem.',
 'Junte a farinha de trigo e o sal.',
 'Comece misturando com uma colher de pau e quando os ingredientes estiverem bem incorporados sove a massa por 15 minutos.',
 'A massa deve ficar lisa, macia e grudando levemente nas mãos. Coloque em uma tigela, cubra com um pano e deixe crescer por 1 hora.',
 'Enquanto isso coloque as salsichas em uma panela, cubra com água e cozinhe por mais 5 minutos a partir do momento que começar a ferver. Desligue o fogo, espere esfriar, corte as salsichas ao meio e reserve.',
 'Após o descanso da massa separe uma porção e corte uma tira retangular e enrole as salsichas na massa.',
 'Coloque em uma assadeira untada com manteiga, coloque as salsichas enroladas com a massa e pincele um pouco de manteiga na superfície.',
 'Leve para assar em forno pré-aquecido a 180 graus por 30 minutos ou até dourar e sirva em seguida. Bom apetite!',
 '',
 14,
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_5_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_6_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_7_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_8_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_9_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/4/8/0/enroladinho_de_salsicha_simples_11084_paso_10_600.webp' ),

 (2,
'Patê de sardinha simples',
'Gabriel Lopes',
CURRENT_TIMESTAMP,
'Para rechear tortas, pães ou servir com torradas como um entradinha: o nosso patê de sardinha simples é uma receita de fácil preparo e deliciosa! Cremoso na medida certa e com poucos ingredientes, essa receita de patê é ideal para os dias corridos ou para receber uma visita de última hora.',
 2,
 1,
 1,
 '1 lata de sardinha',
 '½ cebola ralada',
 '2 cenoura ralada',
 '½ caixa de creme de leite',
 '½ xícara de maionese',
 'sal',
 'coentro ou salsinha',
 '',
 '',
 '',
 'Comece com o pré-preparo do seu patê de sardinha simples: rale a cebola e a cenoura, limpe a sardinha e separe os demais ingredientes.',
 'Coloque a sardinha em uma tigela e amasse com um garfo.',
 'Junte a cenoura e a cebola ralada e misture bem.',
 'Adicione a maionese e o creme de leite aos poucos até ficar na textura desejada. Misture bem mais uma vez. Finalize temperando com sal a gosto e o coentro ou salsinha picada.',
 'Leve à geladeira por 1 hora e sirva em seguida da forma que preferir. Bom apetite!',
 '',
 '',
 '',
 '',
 '',
 '',
 14,
 'https://cdn0.tudoreceitas.com/pt/posts/8/9/0/pate_de_sardinha_simples_11098_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/9/0/pate_de_sardinha_simples_11098_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/9/0/pate_de_sardinha_simples_11098_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/9/0/pate_de_sardinha_simples_11098_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/9/0/pate_de_sardinha_simples_11098_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/9/0/pate_de_sardinha_simples_11098_paso_4_600.webp',
 '',
 '',
 '',
 '',
 '',
 ''),


(3,
 'Bolinho de arroz com legumes',
 'Joao Felicio',
 CURRENT_TIMESTAMP,
 'Nem todo mundo é fã de incluir legumes e verduras na alimentação do dia-a-dia. Um ótimo jeito de mudar isso é diversificar o preparo e a apresentação, "disfarçando" a presença dele. É o caso de desse bolinho de arroz com legumes! Com o arroz cozido do dia anterior, esse preparo reaproveita o alimento evitando que ele seja perdido. A abobrinha italiana e a cenoura ficam responsáveis por deixar esse bolinho ainda mais nutritivo, mas você ainda pode fazer substituições com milho, pepino, nabos, beterrabas ou o que tiver na geladeira. Apesar de ter sido feito no óleo, também fica delicioso se feito na Airfryer ou no forno, o que vai mudar são os tempos de preparo de cada!',
 30,
 2,
 1,
 '100 gramas de Cenoura ralada',
 '150 gramas de Abobrinha italiana ralada',
 '600 gramas de Arroz cozido',
 '85 gramas de Farinha de trigo',
 '2 unidades de Ovos',
 '120 gramas de Queijo mussarela',
 '1 punhado de Sal',
 '1 pitada de Pimenta-do-reino',
 '1 punhado de Óleo',
 '',
 'Vamos começar a preparar o bolinho de arroz? Coloque o arroz cozido em um recipiente e utilize o mixer para deixá-los em grãos menores. Você também pode bater rapidamente no liquidificador ou processador.',
 'Acrescente os ovos e misture bem. O ovo ajudará a dar a liga no bolinho, é importante que ele pegue em todos os grãos.',
 'Adicione o queijo, a abobrinha e a cenoura. Mexa novamente.',
 'Tempere com sal e pimenta-do-reino.',
 'Em seguida, acrescente a farinha de trigo e misture bem.',
 'Molhe as mãos com água e, com auxílio de uma colher, pegue uma porção da massa. Pressione e modele como desejar (bolinha, em formato de quibe) Dica: Aqui, o bolinho ficará bem compactado e não deverá desmanchar. se desmanchar acrescente mais 1 colher de sopa de farinha.',
 'Esquente o óleo em uma frigideira e, quando estiver quente, coloque os bolinhos com cuidado.',
 'Quando estiver dourado, retire e deixe escorrer em uma forma com papel-toalha.',
 'O bolinho pode ser servido ainda quente, acompanhado com o molho de sua preferência, em um delicioso jantar. Se você gostou dessa receita e pretende fazer por aí, nos conta nos comentários que vamos adorar saber!',
 '',
 '',
 14,
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_5_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_6_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_7_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/6/9/bolinho_de_arroz_com_legumes_10966_paso_8_600.webp',
 '',
 ''),


(4,
 'Barquinha de maionese',
 'Gabriel Lopes',
 CURRENT_TIMESTAMP,
 'Ideal para ser servida em festa, essa barquinha de maionese tem um preparo rápido e ficam deliciosas! Com poucos ingredientes, a maionese é simples e super gostosa, sendo também uma ótima opção de receita de acompanhamento no dia a dia. Já a barquinha é fácil de achar em lojas de artigos para festa ou mesmo na internet, com diversos tamanhos e formatos, deixando essa receita perfeita para servir em festas. Esse aperitivo também é conhecido como barquete de maionese. Aprenda a fazer essa barquinha de maionese no nosso post do dia aqui no TudoReceitas e prepare essa delícia na sua próxima festa em casa',
 6,
 3,
 1,
 '2 batatas médias',
 '1 cenoura',
 'coentro',
 'sal',
 'pimenta',
 '4 colheres de sopa de maionese',
 'barquinhas compradas prontas',
 '',
 '',
 '',
 'Vamos começar a fazer a maionese na barquinha? Comece separando os ingredientes. Descasque e corte as batatas e a cenoura em cubos, pique o coentro (que você pode substituir por salsinha se preferir).',
 'Cozinhe as batatas e as cenouras até ficarem macias (mas não desmanchando, nessa receita é importante que mantenham o formato dos cubos). Escorra a água.',
 'Em uma tigela grande coloque a batata e a cenoura cozida, a maionese, o coentro picado e tempere com sal e pimenta a gosto. Misture bem. Sua barca de maionese está quase pronta.',
 'Coloque a maionese nas barquinhas (que podem ser caseiras ou compradas prontas, você encontra em diversos formatos e tamanhos na internet ou em lojas para artigos para festa). Sirva em seguida e bom apetite! Ah, quer mais receitas de entradinhas?',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 14,
 'https://cdn0.tudoreceitas.com/pt/posts/7/6/9/barquinha_de_maionese_10967_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/6/9/barquinha_de_maionese_10967_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/6/9/barquinha_de_maionese_10967_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/6/9/barquinha_de_maionese_10967_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/6/9/barquinha_de_maionese_10967_paso_3_600.webp',
 '',
 '',
 '',
 '',
 '',
 '',
 ''),


(5,
 'Pão com ovo na Airfryer',
 'Joao Felicio',
 CURRENT_TIMESTAMP,
 'Tem dias que a gente acorda e quer um café da manhã mais reforçado. Esse pão com ovo na airfryer fica pronto rapidinho e dá aquele reforço pro seu dia! A Airfryer é super prática e permite o preparo de diversas receitas, sem uso de óleo e em menos tempo. Aqui não foi diferente! Não precisa usar frigideira para preparar o ovo, o queijo ficou douradinho e a gema fica mole, tanto que quando partida, escorre dando um toque final maravilhoso.',
 1,
 1,
 1,
 '1 unidade de Pão francês',
 '1 unidade de Ovo',
 '2 fatias de Queijo muçarela',
 '1 pitada de Sal',
 '1 pitada de Pimenta-do-reino',
 '',
 '',
 '',
 '',
 '',
 'Comece cortando o pão francês ao meio, separando em duas bandas. Dica: Se preferir, você também pode utilizar fatias de pão de forma. Mas, tome cuidado porque ela é mais delicada.',
 'Com auxílio de uma colher de sopa, pressione o miolo para que ele faça um fundo para acomodar o ovo.',
 'Com cuidado para não vazar dos lados, coloque o ovo no pão e adicione o sal e a pimenta-do-reino.',
 'Coloque as fatias de queijo e leve na Airfryer, a 180 graus, por 9 minutos. Dica: nesse tempo, a gema ficará mole. Caso queira ela durinha, deixe por mais 5 minutos.',
 'Retire seu pão com ovo na Airfryer, prepare a mesa e aproveite!',
 'Você pode fazer no café da manhã, lanche da tarde ou da noite. Nos conta nos comentários o que achou e se faria por aí! Bom apetite!',
 '',
 '',
 '',
 '',
 '',
 14,
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/5/8/pao_com_ovo_na_airfryer_10850_paso_5_600.webp',
 '',
 '',
 '',
 '',
 ''),

 (6,
 'Omelete na airfryer',
 'Gabriel Lopes',
 CURRENT_TIMESTAMP,
 'Para os dias corridos, quando não estamos com muito tempo para elaborar pratos mais demorados, a omelete de forno é uma excelente alternativa para que possamos fazer uma boa refeição! Por ser versátil, esse prato nos possibilita uma variedade de combinações nos recheios! Facilitando ainda mais a nossa vida, temos a opção de preparar a omelete na airfryer! E para isso, não há dificuldade, pois a receita é simples e em 25 minutos você terá uma deliciosa omelete para saborear!',
 4,
 2,
 1,
 '4 ovos',
 '½ xícara de presunto em cubinhos',
 '½ xícara de queijo muçarela ralado',
 '½ cebola pequena ralada',
 '4 tomatinhos (cortados ao meio)',
 'sal e pimenta-do-reino (a gosto)',
 'orégano (a gosto)',
 'cheiro verde ou manjericão fresco (a gosto)',
 'azeite de oliva (para pincelar)',
 '',
 'Para preparar a omelete na airfryer, comece separando os ingredientes necessários. Dica: Você poderá incluir outros ingredientes na receita, como: milho, ervilha, azeitonas...',
 'Bata os ovos ligeiramente com um fouet.',
 'Adicione os demais ingredientes: presunto, queijo e cebola ralada.',
 'Tempere com sal, pimenta-do-reino e orégano.',
 'Misture tudo muito bem e transfira a massa para um refratário (que caiba dentro do cesto da airfryer, podendo ser de vidro, de silicone ou até de alumínio) untado com azeite de oliva. Dica: Neste momento preaqueça a airfryer a 200 graus por 5 minutos.',
 'Decore a omelete com tomatinhos cortados ao meio e cheiro verde ou folhas de manjericão picados. Acomode o refratário no cesto do aparelho.',
 'Reduza a temperatura da airfryer para 180 graus e asse a omelete por cerca de 15 minutos.',
 'Após esse tempo, abra e verifique se a omelete está pronta. Caso seja necessário, retorne para assar por mais 5 - 7 minutos ou até que ao espetar um garfo ele esteja firme em cima e cremoso no centro.',
 'Pronto! Sua omelete na airfryer está pronta para ser saboreada! Sirva com uma saladinha fresca e se delicie!',
 'Esperamos que tenha apreciado essa receita prática de omelete na airfryer! Bom apetite!',
 '',
 13,
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_5_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_6_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_7_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_8_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/7/8/0/omelete_na_airfryer_11087_paso_9_600.webp',
 ''),

 (7,
 'Hash de batata doce com ovo',
 'Joao Felicio',
 CURRENT_TIMESTAMP,
 'Hash de batata doce é um jeito tipicamente norte-americano de preparar esse ingrediente superversátil. Cortada em cubos pequenos, a batata doce é complementada com ovo e ganha muito sabor com ingredientes simples como alho, cebola e, aqui na nossa versão, um toque de pimenta caiena. Preparado em uma panela só, essa receita de hash de batata doce com ovo é ideal para o dia a dia: rápida, prática e deliciosa.',
 1,
 2,
 1,
 '1 batata doce',
 '1 ovo',
 '½ cebola pequena',
 '1 dente de alho',
 '½ colher de chá de pimenta caiena',
 '1 pitada de colorau',
 'sal',
 'azeite',
 'coentro',
 '',
 'Separe os ingredientes. Pique o alho e a cebola.',
 'Corte a batata doce em cubos pequenos.',
 'Leve uma frigideira ao fogo médio e refogue o alho e a cebola no azeite. Assim que dourar, adicione a pimenta caiena e o colorau. Misture bem.',
 'Junte a batata doce em cubos, misture bem para que todos os pedaços peguem o sabor do refogado e tempere com sal a gosto. Cozinhe até a batata ficar macia macia (se necessário, adicione mais um fio de azeite).',
 'Abra um buraco no meio da panela e adicione o ovo. Tampe a panela e cozinhe até chegar ao ponto desejado: com a gema mole ou bem cozida.',
 'Desligue o fogo e finalize com coentro picado. Sirva em seguida e bom apetite!',
 '',
 '',
 '',
 '',
 '',
 13,
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/1/5/7/hash_de_batata_doce_com_ovo_10751_paso_5_600.webp',
 '',
 '',
 '',
 '',
 ''),


(8,
 'Batata doce com ovo no forno',
 'Gabriel Lopes',
 CURRENT_TIMESTAMP,
 'Essa deliciosa combinação de batata doce com ovo ganha ainda mais sabor ao ser preparada no forno, como uma fritada. É uma receita excelente para ser preparada como acompanhamento de um frango ou de um peixe grelhado, pois é bem leve e versátil! Além disso, é muito simples de ser preparada! Você vai precisar de batata doce, ovos, cebola, queijo, creme de leite, alguns temperinhos e pronto! Terá uma refeição completa para introduzir no seu cardápio ou para levar na marmita!',
 4,
 3,
 1,
 '1 colher de sopa de azeite de oliva',
 '3 ovos grandes',
 '350 gramas de batata doce cozida em cubinhos',
 '½ cebola roxa pequena',
 '½ xícara de queijo mussarela picado ou ralado',
 '½ caixa de creme de leite',
 'sal e pimenta do reino (a gosto)',
 'queijo parmesão ralado (a gosto)',
 'cheiro verde picado (a gosto)',
 'manjericão seco ou fresco (a gosto)',
 'Separe todos os ingredientes necessários para preparar essa receita de fritada de batata doce no forno.',
 'Num bowl, bata os ovos com sal, pimenta do reino e manjericão com o auxílio de um fouet. Dica: Pré aqueça o forno a 180 graus neste momento.',
 'Adicione o queijo mussarela, a cebola, o cheiro verde e o creme de leite e misture mais um pouco.',
 'Num refratário pequeno, pincele azeite de oliva e acomode a batata doce cozida em cubinhos. Em seguida, cubra com a mistura preparada anteriormente.',
 'Polvilhe queijo parmesão ralado.',
 'Leve para assar em forno pré aquecido a 180 graus por 30 minutos ou até dourar levemente.',
 'Sua receita com batata doce e ovo no forno está pronta para ser saboreada. Você irá se surpreender com o sabor!',
 'Esperamos que tenha gostado da receita! Bom apetite!',
 '',
 '',
 '',
 13,
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_5_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_6_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/0/4/7/batata_doce_com_ovo_no_forno_10740_paso_7_600.webp',
 '',
 '',
 ''),


(9,
 'Ovo cozido recheado',
 'Joao Felicio',
 CURRENT_TIMESTAMP,
 'Hoje é dia de receita bem rápida e super simples pra você servir de entrada ou acompanhamento: ovos cozidos recheados. Usando a mesma base nós vamos preparar 3 sabores de recheio nessa receita que vai levar menos de 30 minutos para ficar pronta. Com ingredientes simples como mostarda, azeitona e orégano, você consegue preparar esses deliciosos ovos recheados no dia a dia - e pode usar a criatividade e usar também outros temperos que tiver em casa.',
 2,
 2,
 1,
 '3 ovos cozidos',
 '80 gramas de maionese',
 'páprica doce',
 'orégano',
 '2 colherões de azeitonas pretas',
 '1 colher de sopa de mostarda',
 '',
 '',
 '',
 '',
 'Comece separando os ingredientes.',
 'Cozinhe os ovos por 15 minutos a partir do momento que a água ferver. Espere amornar e descasque com delicadeza.',
 'Corte ao meio, retire a gema e reserve as claras cozidas.',
 'Amasse as gemas cozidas com um garfo.',
 'E em seguida, misture na maionese. Essa será a base para os 3 sabores dos nossos ovos recheados, então divida essa mistura em 3 tigelas diferentes.',
 'O primeiro sabor será a nossa base com um toque picante da páprica doce. Basta rechear a clara cozida com a base e finalizar com uma pitada do tempero.',
 'O segundo recheio será a base + azeitonas pretas. Basta misturar as azeitonas picadas na base e rechear a clara cozida.',
 'O terceiro sabor será a base mais um toque de mostarda e finalizada com orégano. Basta misturar a mostarda na base e rechear a clara cozida. Finalize com o orégano a gosto.',
 'E é só isso! Seus ovos cozidos recheados estão prontos! Bom apetite!',
 '',
 '',
 13,
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_4_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_5_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_6_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_7_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/6/5/7/ovo_cozido_recheado_3_sugestoes_de_recheio_10756_paso_8_600.webp',
 '',
 ''),

 (10,
 'Salada de ovo cozido ralado',
 'Gabriel Lopes',
 CURRENT_TIMESTAMP,
 'Você sempre quis saber como fazer salada de ovo cozido ralada? Essa receita é prática e econômica para você preparar já para o almoço de hoje. Com poucos ingredientes, nossa salada de ovo cozido simples é feita com ele ralado! Trata-se de uma opção maravilhosa para o dia a dia e você pode complementar com os temperos que desejar e tiver em casa. A receita é individual, mas você pode dobrar a quantidade de ingredientes se quiser preparar para mais pessoas.',
 1,
 2,
 1,
 '2 ovos cozidos',
 '1 tomate italiano',
 '2 folhas de alface',
 'sal',
 'pimenta',
 'orégano',
 'azeite',
 '',
 '',
 '',
 'Separe os ingredientes. Cozinhe o ovo na água por 10 minutos a partir do momento que a panela ferver. Corte o tomate em cubos e a alface em tiras.',
 'Quando o ovo estiver cozido, passe-o pelo ralador.',
 'Coloque os 3 ingredientes em uma tigela.',
 'E tempere com sal, pimenta, orégano e azeite.',
 'Sirva em seguida como acompanhamento no almoço e bom apetite!',
 '',
 '',
 '',
 '',
 '',
 '',
 13,
 'https://cdn0.tudoreceitas.com/pt/posts/8/2/7/salada_de_ovo_cozido_ralado_10728_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/2/7/salada_de_ovo_cozido_ralado_10728_paso_0_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/2/7/salada_de_ovo_cozido_ralado_10728_paso_1_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/2/7/salada_de_ovo_cozido_ralado_10728_paso_2_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/2/7/salada_de_ovo_cozido_ralado_10728_paso_3_600.webp',
 'https://cdn0.tudoreceitas.com/pt/posts/8/2/7/salada_de_ovo_cozido_ralado_10728_paso_4_600.webp',
 '',
 '',
 '',
 '',
 '',
 '');